Repository mglantz/ansible-roadshow, pull requests merged in 2018-09, with the labels that each got.

#97 Added simple echo of variables into .bashrc, making the LAB_DIR and W…
  labs/lab-0/README.md
  labs/lab-8/README.md
Labels: enhancement

#100 rename mypassword -> .mypassword to match the instructions in lab 5
  labs/lab-5/README.md
Labels: bug

#105 Change systemd unit files location
  labs/lab-3/README.md
  labs/lab-5/README.md
  labs/lab-solutions/roles/wildflyapp/tasks/main.yml
Labels: bug, ok to merge

#193 Typo
  labs/lab-6/README.md
  labs/lab-7/README.md
  labs/lab-9/README.md
Labels: enhancement
